services:
  postgres-quote:
    image: postgres:16
    container_name: postgres-quote
    restart: unless-stopped
    ports:
      - "${POSTGRES_QUOTE_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_QUOTE_DB}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    volumes:
      - ./postgres-data/postgres-quote:/var/lib/postgresql/data

  postgres-approval:
    image: postgres:16
    container_name: postgres-approval
    restart: unless-stopped
    ports:
      - "${POSTGRES_APPROVAL_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_APPROVAL_DB}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    volumes:
      - ./postgres-data/postgres-approval:/var/lib/postgresql/data

