ALTER TABLE quote ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE quote ADD COLUMN created_by VARCHAR(255) NOT NULL ;
ALTER TABLE quote ADD COLUMN updated_by VARCHAR(255);
ALTER TABLE quote ADD COLUMN updated_at TIMESTAMP ;


ALTER TABLE quote_item ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT now();
ALTER TABLE quote_item ADD COLUMN created_by VARCHAR(255) NOT NULL ;
ALTER TABLE quote_item ADD COLUMN updated_by VARCHAR(255);
ALTER TABLE quote_item ADD COLUMN updated_at TIMESTAMP ;